Los datos son tomados de Klymiuk y colaboradores (2017) y el SRA con código de acceso PRJEB22107.

In [ ]:
!pip install python-docx pandas

Requirement already satisfied: python-docx in /usr/local/lib/python3.12/dist-packages (1.2.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: lxml>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from python-docx) (6.0.2)
Requirement already satisfied: typing_extensions>=4.9.0 in /usr/local/lib/python3.12/dist-packages (from python-docx) (4.15.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
from docx import Document
import pandas as pd
from google.colab import drive
import os
import re
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#Funciones
def df_word(word):
  lines = [p.text.strip() for p in word.paragraphs if p.text.strip() != ""]
  rows = [re.split(r'\t+', line) for line in lines]
#index 1 contain the headers, data starts from index 2
  df = pd.DataFrame(rows[2:], columns=rows[1])
  return df

def normalize_sample_id(sample):
  #isaplha() checks for alphabetic letters
  #this code is very specific for the name of our samples
    if len(sample) == 8 and sample[-1].isalpha():
        return sample[:4] + '-' + sample[4:-1] + '-' + sample[-1]
    else:
        return sample[:4] + '-' + sample[4:]

In [ ]:
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [ ]:
BASE_PATH = '/content/drive/MyDrive/semestres/segundo-semestre/redes_neuronales/proyecto/data'
sra_run_table = pd.read_csv(f'{BASE_PATH}/SraRunTable.csv')
srr_acc_list = pd.read_csv(f'{BASE_PATH}/SRR_Acc_List.txt')
t1 = Document(f'{BASE_PATH}/Table1.DOCX')
dft2 = pd.read_excel(f'{BASE_PATH}/Table2.XLSX',decimal=',')
t3 = Document(f'{BASE_PATH}/Table3.DOCX')
dft4 = pd.read_excel(f'{BASE_PATH}/Table4.XLSX',decimal=',')
dft1 = df_word(t1)
dft3 = df_word(t3)

In [ ]:
sra_run_table

,Run,Assay Type,AvgSpotLen,Bases,BioProject,BioSample,Bytes,Center Name,Collection_Date,common_name,...,Platform,project_name,ReleaseDate,create_date,version,Sample Name,Sample_name,Sequencing_method,SRA Study,Submitter_Id
0,ERR2092801,AMPLICON,500,49231976,PRJEB22107,SAMEA104208451,30233935,MEDICAL UNIVERSITY GRAZ,2015,human,...,ILLUMINA,The human gastric microbiome,2018-01-26T00:00:00Z,2018-01-29T13:39:00Z,1,SAMEA104208451,MPnegCo1,pyrosequencing,ERP024440,MPnegCo1
1,ERR2092802,AMPLICON,500,10109470,PRJEB22107,SAMEA104208452,6257670,MEDICAL UNIVERSITY GRAZ,2015,human,...,ILLUMINA,The human gastric microbiome,2018-01-26T00:00:00Z,2022-07-22T15:58:00Z,2,SAMEA104208452,MPnegCo2,pyrosequencing,ERP024440,MPnegCo2
2,ERR2092803,AMPLICON,501,20604460,PRJEB22107,SAMEA104208453,12267412,MEDICAL UNIVERSITY GRAZ,2015,human,...,ILLUMINA,The human gastric microbiome,2018-01-26T00:00:00Z,2022-07-22T10:44:00Z,2,SAMEA104208453,P001Z12,pyrosequencing,ERP024440,P001Z12
3,ERR2092804,AMPLICON,501,23559583,PRJEB22107,SAMEA104208454,13914641,MEDICAL UNIVERSITY GRAZ,2015,human,...,ILLUMINA,The human gastric microbiome,2018-01-26T00:00:00Z,2022-07-18T01:32:00Z,2,SAMEA104208454,P001Z13,pyrosequencing,ERP024440,P001Z13
4,ERR2092805,AMPLICON,501,12452832,PRJEB22107,SAMEA104208455,7426793,MEDICAL UNIVERSITY GRAZ,2015,human,...,ILLUMINA,The human gastric microbiome,2018-01-26T00:00:00Z,2022-07-21T13:55:00Z,2,SAMEA104208455,P001Z14,pyrosequencing,ERP024440,P001Z14
5,ERR2092806,AMPLICON,501,29376711,PRJEB22107,SAMEA104208456,17356891,MEDICAL UNIVERSITY GRAZ,2015,human,...,ILLUMINA,The human gastric microbiome,2018-01-26T00:00:00Z,2022-07-14T08:08:00Z,2,SAMEA104208456,P001Z18,pyrosequencing,ERP024440,P001Z18
6,ERR2092807,AMPLICON,500,8199351,PRJEB22107,SAMEA104208457,5123196,MEDICAL UNIVERSITY GRAZ,2015,human,...,ILLUMINA,The human gastric microbiome,2018-01-26T00:00:00Z,2022-07-19T01:14:00Z,2,SAMEA104208457,P002Z18,pyrosequencing,ERP024440,P002Z18
7,ERR2092808,AMPLICON,501,8778617,PRJEB22107,SAMEA104208458,5273647,MEDICAL UNIVERSITY GRAZ,2015,human,...,ILLUMINA,The human gastric microbiome,2018-01-26T00:00:00Z,2022-07-19T01:14:00Z,2,SAMEA104208458,P003Z10,pyrosequencing,ERP024440,P003Z10
8,ERR2092809,AMPLICON,500,32818855,PRJEB22107,SAMEA104208459,19769896,MEDICAL UNIVERSITY GRAZ,2015,human,...,ILLUMINA,The human gastric microbiome,2018-01-26T00:00:00Z,2022-07-17T05:57:00Z,2,SAMEA104208459,P003Z15,pyrosequencing,ERP024440,P003Z15
9,ERR2092810,AMPLICON,500,12283542,PRJEB22107,SAMEA104208460,7687177,MEDICAL UNIVERSITY GRAZ,2015,human,...,ILLUMINA,The human gastric microbiome,2018-01-26T00:00:00Z,2022-07-18T01:17:00Z,2,SAMEA104208460,P004Z10-WH,pyrosequencing,ERP024440,P004Z10-WH
10,ERR2092811,AMPLICON,501,24219840,PRJEB22107,SAMEA104208461,14218552,MEDICAL UNIVERSITY GRAZ,2015,human,...,ILLUMINA,The human gastric microbiome,2018-01-26T00:00:00Z,2022-08-01T23:37:00Z,2,SAMEA104208461,P004Z17,pyrosequencing,ERP024440,P004Z17
11,ERR2092812,AMPLICON,500,7794578,PRJEB22107,SAMEA104208462,4845270,MEDICAL UNIVERSITY GRAZ,2015,human,...,ILLUMINA,The human gastric microbiome,2018-01-26T00:00:00Z,2022-07-13T21:22:00Z,2,SAMEA104208462,P005Z08,pyrosequencing,ERP024440,P005Z08
12,ERR2092813,AMPLICON,501,22727728,PRJEB22107,SAMEA104208463,13805977,MEDICAL UNIVERSITY GRAZ,2015,human,...,ILLUMINA,The human gastric microbiome,2018-01-26T00:00:00Z,2022-07-13T02:01:00Z,2,SAMEA104208463,P007Z08,pyrosequencing,ERP024440,P007Z08
13,ERR2092814,AMPLICON,500,20714918,PRJEB22107,SAMEA104208464,12103951,MEDICAL UNIVERSITY GRAZ,2015,human,...,ILLUMINA,The human gastric microbiome,2018-01-26T00:00:00Z,2022-07-30T17:53:00Z,2,SAMEA104208464,P008Z08,pyrosequencing,ERP024440,P008Z08
14,ERR2092815,AMPLICON,500,15734289,PRJEB22107,SAMEA104208465,8614942,MEDICAL UNIVERSITY GRAZ,2015,human,...,ILLUMINA,The human gastric microbiome,2018-01-26T00:00:00Z,2022-07-13T10:44:00Z,2,SAMEA104208465,P008Z17,pyrosequencing,ERP024440,P008Z17
15,ERR2092816,AMPLICON,500,16074845,PRJEB22107,SAMEA104208466,8586234,MEDICAL UNIVERSITY GRAZ,2015,human,...,ILLUMINA,The human gastric microbiome,2018-01-26T00:00:00Z,2022-07-30T05:43:00Z,2,SAMEA104208466,P021Z12,pyrosequencing,ERP024440,P021Z12
16,ERR2092817,AMPLICON,500,28001933,PRJEB22107,SAMEA104208467,15134037,MEDICAL UNIVERSITY GRAZ,2015,human,...,ILLUMINA,The human gastric microbiome,2018-01-26T00:00:00Z,2022-07-30T17:53:00Z,2,SAMEA104208467,P022Z12,pyrosequencing,ERP024440,P022Z12
17,ERR2092818,AMPLICON,500,112268637,PRJEB22107,SAMEA104208468,62292520,MEDICAL UNIVERSITY GRAZ,2015,human,...,ILLUMINA,The human gastric microbiome,2018-01-26T00:00:00Z,2022-07-17T05:57:00Z,2,SAMEA104208468,P022Z13,pyrosequencing,ERP024440,P022Z13
18,ERR2092819,AMPLICON,500,36632894,PRJEB22107,SAMEA104208469,21601820,MEDICAL UNIVERSITY GRAZ,2015,human,...,ILLUMINA,The human gastric microbiome,2018-01-26T00:00:00Z,2022-07-17T10:57:00Z,2,SAMEA104208469,P022Z17,pyrosequencing,ERP024440,P022Z17
19,ERR2092820,AMPLICON,500,7718512,PRJEB22107,SAMEA104208470,4093162,MEDICAL UNIVERSITY GRAZ,2015,human,...,ILLUMINA,The human gastric microbiome,2018-01-26T00:00:00Z,2022-07-30T17:53:00Z,2,SAMEA104208470,P029Z13,pyrosequencing,ERP024440,P029Z13
20,ERR2092821,AMPLICON,500,16131256,PRJEB22107,SAMEA104208471,9216882,MEDICAL UNIVERSITY GRAZ,2015,human,...,ILLUMINA,The human gastric microbiome,2018-01-26T00:00:00Z,2022-07-19T01:14:00Z,2,SAMEA104208471,P033Z12,pyrosequencing,ERP024440,P033Z12
21,ERR2092822,AMPLICON,500,46593525,PRJEB22107,SAMEA104208472,26048296,MEDICAL UNIVERSITY GRAZ,2015,human,...,ILLUMINA,The human gastric microbiome,2018-01-26T00:00:00Z,2022-07-20T19:17:00Z,2,SAMEA104208472,P045Z10A,pyrosequencing,ERP024440,P045Z10A
22,ERR2092823,AMPLICON,500,7829274,PRJEB22107,SAMEA104208473,4301869,MEDICAL UNIVERSITY GRAZ,2015,human,...,ILLUMINA,The human gastric microbiome,2018-01-26T00:00:00Z,2022-07-30T05:43:00Z,2,SAMEA104208473,P047Z15,pyrosequencing,ERP024440,P047Z15
23,ERR2092824,AMPLICON,500,9243209,PRJEB22107,SAMEA104208474,5058686,MEDICAL UNIVERSITY GRAZ,2015,human,...,ILLUMINA,The human gastric microbiome,2018-01-26T00:00:00Z,2022-07-15T05:41:00Z,2,SAMEA104208474,P052Z10,pyrosequencing,ERP024440,P052Z10
24,ERR2092825,AMPLICON,500,17259181,PRJEB22107,SAMEA104208475,10244546,MEDICAL UNIVERSITY GRAZ,2015,human,...,ILLUMINA,The human gastric microbiome,2018-01-26T00:00:00Z,2022-07-22T12:50:00Z,2,SAMEA104208475,P058Z14,pyrosequencing,ERP024440,P058Z14
25,ERR2092826,AMPLICON,500,9807008,PRJEB22107,SAMEA104208476,5488086,MEDICAL UNIVERSITY GRAZ,2015,human,...,ILLUMINA,The human gastric microbiome,2018-01-26T00:00:00Z,2022-07-14T06:13:00Z,2,SAMEA104208476,P060Z15,pyrosequencing,ERP024440,P060Z15
26,ERR2092827,AMPLICON,500,44278723,PRJEB22107,SAMEA104208477,25105171,MEDICAL UNIVERSITY GRAZ,2015,human,...,ILLUMINA,The human gastric microbiome,2018-01-26T00:00:00Z,2022-07-30T17:53:00Z,2,SAMEA104208477,P061Z10,pyrosequencing,ERP024440,P061Z10
27,ERR2092828,AMPLICON,500,11724328,PRJEB22107,SAMEA104208478,6290365,MEDICAL UNIVERSITY GRAZ,2015,human,...,ILLUMINA,The human gastric microbiome,2018-01-26T00:00:00Z,2022-07-19T01:14:00Z,2,SAMEA104208478,P062Z14,pyrosequencing,ERP024440,P062Z14
28,ERR2092829,AMPLICON,500,36526377,PRJEB22107,SAMEA104208479,21007071,MEDICAL UNIVERSITY GRAZ,2015,human,...,ILLUMINA,The human gastric microbiome,2018-01-26T00:00:00Z,2022-07-14T09:57:00Z,2,SAMEA104208479,P066Z10,pyrosequencing,ERP024440,P066Z10
29,ERR2092830,AMPLICON,500,29378827,PRJEB22107,SAMEA104208480,17768344,MEDICAL UNIVERSITY GRAZ,2015,human,...,ILLUMINA,The human gastric microbiome,2018-01-26T00:00:00Z,2022-07-20T01:02:00Z,2,SAMEA104208480,P080Z15,pyrosequencing,ERP024440,P080Z15
30,ERR2092831,AMPLICON,500,9956892,PRJEB22107,SAMEA104208481,5691753,MEDICAL UNIVERSITY GRAZ,2015,human,...,ILLUMINA,The human gastric microbiome,2018-01-26T00:00:00Z,2022-07-30T17:53:00Z,2,SAMEA104208481,P107Z15,pyrosequencing,ERP024440,P107Z15
31,ERR2092832,AMPLICON,500,6798095,PRJEB22107,SAMEA104208482,3848354,MEDICAL UNIVERSITY GRAZ,2015,human,...,ILLUMINA,The human gastric microbiome,2018-01-26T00:00:00Z,2022-07-14T15:47:00Z,2,SAMEA104208482,P121Z15,pyrosequencing,ERP024440,P121Z15

In [ ]:
dft1

,level,taxon,comparison,mean1,mean2,pvalue,adj.pvalue,sig
0,Phylum,Actinobacteria,Hp- vs. Hp+/CagA-,0.1060,0.0332,0.0050,0.0094,**
1,Phylum,Actinobacteria,Hp- vs. Hp+/CagA+,0.1060,0.0113,0.0002,0.0006,***
2,Phylum,Actinobacteria,Hp+/CagA- vs. Hp+/CagA+,0.0332,0.0113,0.2293,0.2866,None
3,Phylum,Bacteroidetes,Hp- vs. Hp+/CagA-,0.2919,0.0430,0.0009,0.0019,**
4,Phylum,Bacteroidetes,Hp- vs. Hp+/CagA+,0.2919,0.0294,0.0007,0.0017,**
...,...,...,...,...,...,...,...,...
142,Genus,Streptococcus,Hp- vs. Hp+/CagA+,0.1896,0.0185,0.0014,0.0100,*
143,Genus,Streptococcus,Hp+/CagA- vs. Hp+/CagA+,0.0603,0.0185,0.1188,0.1716,None
144,Genus,Veillonella,Hp- vs. Hp+/CagA-,0.0619,0.0145,0.0015,0.0100,*
145,Genus,Veillonella,Hp- vs. Hp+/CagA+,0.0619,0.0114,0.0006,0.0081,**
146,Genus,Veillonella,Hp+/CagA- vs. Hp+/CagA+,0.0145,0.0114,0.7181,0.7370,None

In [ ]:
dft2

,kingdom,phylum,class,order,family,genus,# OTUs,species,P001Z12,P001Z13,...,P008Z08,P021Z12,P022Z17,P029Z13,P045Z10A,P047Z15,P060Z15,P061Z10,P062Z14,P121Z15
0,k__Bacteria,p__Firmicutes,c__Bacilli,o__Lactobacillales,f__Streptococcaceae,g__Streptococcus,103,s__alactolyticus;s__anginosus;s__infantis;s__s...,0.190581,0.298446,...,0.017731,0.002377,0.004464,0.010444,0.031285,0.003381,0.042707,0.010215,0.001565,0.061214
1,k__Bacteria,p__Bacteroidetes,c__Bacteroidia,o__Bacteroidales,f__Prevotellaceae,g__Prevotella,86,s__copri;s__intermedia;s__melaninogenica;s__na...,0.139397,0.084351,...,0.055815,0.002485,0.011565,0.031708,0.006547,0.009166,0.026263,0.000696,0.000978,0.055244
2,k__Bacteria,p__Actinobacteria,c__Actinobacteria,o__Actinomycetales,f__Actinomycetaceae,g__Actinomyces,50,NaN,0.048744,0.087595,...,0.023244,0.000216,0.000271,0.002404,0.001413,0.000902,0.019574,0.001064,0.000391,0.014078
3,k__Bacteria,p__Proteobacteria,c__Epsilonproteobacteria,o__Campylobacterales,f__Helicobacteraceae,g__Helicobacter,38,s__pylori,0.000034,0.000463,...,0.803767,0.977492,0.964272,0.912465,0.907772,0.968595,0.784132,0.951709,0.984744,0.765660
4,k__Bacteria,p__Firmicutes,c__Clostridia,o__Clostridiales,f__Lachnospiraceae,g__,33,NaN,0.002095,0.003408,...,0.001013,0.000108,0.000000,0.000451,0.000000,0.000075,0.000061,0.000000,0.000733,0.001158
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
309,k__Bacteria,p__Synergistetes,c__Synergistia,o__Synergistales,f__Dethiosulfovibrionaceae,g__Pyramidobacter,1,s__piscolens,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
310,k__Bacteria,p__TM7,c__TM7-1,o__,f__,g__,1,NaN,0.000000,0.000218,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
311,k__Bacteria,p__TM7,c__TM7-3,Other,Other,Other,1,NaN,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
312,k__Bacteria,p__Tenericutes,c__Mollicutes,o__Acholeplasmatales,f__Acholeplasmataceae,g__,1,NaN,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
313,k__Bacteria,p__[Thermi],c__Deinococci,o__Deinococcales,f__Trueperaceae,g__Truepera,1,NaN,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [ ]:
dft3

               Type                   Comparison  Effect      SD      N
0             chao1       H.p.-  vs. H.p.+/CagA-  43.549  89.046     67
1             chao1        H.p.- vs. H.p.+/CagA+  63.735  48.454     11
2             chao1  H.p.+/CagA- vs. H.p.+/CagA+  20.186  89.046    307
3  observed_species        H.p.- vs. H.p.+/CagA-  55.633  72.593     28
4  observed_species       H.p.-  vs. H.p.+/CagA+  73.633  49.376      9
5  observed_species  H.p.+/CagA- vs. H.p.+/CagA+  18.000  72.593    257
6     PD_whole_tree        H.p.- vs. H.p.+/CagA-   2.898   3.080     19
7     PD_whole_tree        H.p.- vs. H.p.+/CagA+   2.982   1.986      9
8     PD_whole_tree  H.p.+/CagA- vs. H.p.+/CagA+   0.084   3.080  21162

In [ ]:
t4

,ID,Taxon,P001Z12,P001Z13,P001Z14,P001Z18,P002Z18,P003Z10,P004Z17,P005Z08WH2,...,P021Z12,P022Z17,P029Z13,P045Z10A,P047Z15,P060Z15,P061Z10,P062Z14,P121Z15,Summe
0,232.0,k__Bacteria;p__Proteobacteria;c__Betaproteobac...,0.000996,0.000191,0.000289,0.000222,0.014049,0.000366,0.000000,0.000000,...,0,0,0,0,0,0,0,0,0,0.000556
1,239.0,k__Bacteria;p__Proteobacteria;c__Betaproteobac...,0.001134,0.000000,0.000520,0.000533,0.012391,0.000586,0.000000,0.000000,...,0,0,0,0,0,0,0,0,0,0.000523
2,218.0,k__Bacteria;p__Proteobacteria;c__Betaproteobac...,0.001099,0.000055,0.000520,0.000000,0.012129,0.000440,0.000000,0.000000,...,0,0,0,0,0,0,0,0,0,0.000491
3,255.0,k__Bacteria;p__Proteobacteria;c__Deltaproteoba...,0.000000,0.000000,0.000000,0.000000,0.013351,0.000000,0.000000,0.000000,...,0,0,0,0,0,0,0,0,0,0.000460
4,235.0,k__Bacteria;p__Proteobacteria;c__Betaproteobac...,0.000962,0.000109,0.001560,0.000244,0.008639,0.000879,0.000000,0.000000,...,0,0,0,0,0,0,0,0,0,0.000427
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,253.0,k__Bacteria;p__Proteobacteria;c__Deltaproteoba...,0.000000,0.000055,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0,0,0,0,0,0,0,0,0,0.000002
62,254.0,k__Bacteria;p__Proteobacteria;c__Deltaproteoba...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000051,0.000000,...,0,0,0,0,0,0,0,0,0,0.000002
63,87.0,k__Bacteria;p__Firmicutes;c__Bacilli;Other;Oth...,0.000000,0.000000,0.000000,0.000044,0.000000,0.000000,0.000000,0.000000,...,0,0,0,0,0,0,0,0,0,0.000002
64,302.0,k__Bacteria;p__Spirochaetes;c__[Leptospirae];o...,0.000000,0.000000,0.000000,0.000044,0.000000,0.000000,0.000000,0.000000,...,0,0,0,0,0,0,0,0,0,0.000002
65,NaN,NaN,0.013981,0.001445,0.010633,0.002796,0.104799,0.003516,0.007893,0.009166,...,0,0,0,0,0,0,0,0,0,NaN

In [ ]:
data = {
    "Sample_ID": [
        "P005-Z08","P002-Z18","P003-Z10","P001-Z14","P004-Z10e",
        "P001-Z12","P007-Z08","P001-Z13","P004-Z17","P001-Z18",
        "P052-Z10","P107-Z15","P033-Z12","P008-Z17","P058-Z14",
        "P080-Z15","P003-Z15","P022-Z12","P066-Z10","P022-Z13",
        "P121-Z15","P029-Z13","P047-Z15","P060-Z15","P062-Z14",
        "P021-Z12","P008-Z08","P022-Z17","P061-Z10","P045-Z10-A"
    ],
    "Reads": [
        11346,11460,13651,17305,18310,
        29111,35447,36680,39276,45063,
        15743,16451,26728,26941,27627,
        44882,48255,48502,57636,188261,
        11223,13309,13310,16297,20451,
        27768,33557,59142,73327,79271
    ],
    "Hp_CagA_Status": [
        "H.p.-","H.p.-","H.p.-","H.p.-","H.p.-",
        "H.p.-","H.p.-","H.p.-","H.p.-","H.p.-",
        "H.p.+/CagA-","H.p.+/CagA-","H.p.+/CagA-","H.p.+/CagA-","H.p.+/CagA-",
        "H.p.+/CagA-","H.p.+/CagA-","H.p.+/CagA-","H.p.+/CagA-","H.p.+/CagA-",
        "H.p.+/CagA+","H.p.+/CagA+","H.p.+/CagA+","H.p.+/CagA+","H.p.+/CagA+",
        "H.p.+/CagA+","H.p.+/CagA+","H.p.+/CagA+","H.p.+/CagA+","H.p.+/CagA+"
    ],
    "Age": [
        23,38,56,56,83,
        54,50,66,27,50,
        50,51,66,34,43,
        76,69,75,64,71,
        33,37,40,59,51,
        21,32,50,32,51
    ],
    "Sex": [
        "F","F","M","F","M",
        "M","M","M","M","M",
        "F","M","F","F","M",
        "F","F","F","M","F",
        "M","F","M","F","F",
        "F","M","M","F","M"
    ],
    "Indication": [
        "cd","rs","uap","uap","bl",
        "uap","uap","rs","uap","un",
        "un","rs","un","uap","rs",
        "uap","cu","un","bl","cu",
        "uap","rs","uap","rs","rs",
        "ibs","uap","an","ibs","bl"
    ],
    "Diagnosis": [
        "nf","g, r","g","ci","g, r, u",
        "g, r, öv","r","nf","nf","r",
        "g","g, r, he","g, r","nf","g, ci",
        "g, he","g","g, he, di","g, he","g",
        "g","nf","g, ud","g, r","ci",
        "g","g","nf","g, di, l","g"
    ],
    "Score": [
        "na","na","na","na","na",
        "na","na","na","na","na",
        "3+","2+","1+","2+","3+",
        "2+","2+","3+","2+","2+",
        "2+","3+","2+","2+","3+",
        "3+","3+","2+","3+","3+"
    ]
}
terms_indication={"an": "anemia",
                          "bl":"bleeding",
                          "cd":"celiac disease",
                          "cu":"check-up",
                          "ibs": "irritable bowel syndrome",
                          "rs":"reflux",
                          "uap":"upper abdominal pain",
                          "un":"unknown"}

terms_quiime={"na":"not aplicable",
              "e":"not included to statistical analysis"}
terms_diagnosis={"ci": "cardial insufficiency",
                 "di": "duodenal inflammation",
                 "g": "gastritis",
                 "he": "hernia",
                 "l": "lymphoedema",
                 "nf":"no finding",
                 "öv":"ösophagus varizen",
                 "r":"reflux",
                 "u":"ulcer",
                 "ud":"ulcer duodenum"}

patients_df=pd.DataFrame(data)
dfp=patients_df


dfp["Diagnosis"] = (
    dfp["Diagnosis"]
        .str.split(",")
        .apply(lambda x: [terms_diagnosis.get(i.strip(), i.strip()) for i in x])
        .str.join(", ")
)

for i in dfp:
  if i=="Indication":
     dfp['Indication']=dfp['Indication'].replace(terms_indication)
  if i=='Score':
      dfp['Score']=dfp['Score'].replace(terms_quiime)

#Según la literatura, los autores no tuvieron en cuenta al paciente
#P004-Z10 porque su condición alteraba los datos.
dfp=dfp[dfp["Sample_ID"] != "P004-Z10e"]
dfp

,Sample_ID,Reads,Hp_CagA_Status,Age,Sex,Indication,Diagnosis,Score
0,P005-Z08,11346,H.p.-,23,F,celiac disease,no finding,not aplicable
1,P002-Z18,11460,H.p.-,38,F,reflux,"gastritis, reflux",not aplicable
2,P003-Z10,13651,H.p.-,56,M,upper abdominal pain,gastritis,not aplicable
3,P001-Z14,17305,H.p.-,56,F,upper abdominal pain,cardial insufficiency,not aplicable
5,P001-Z12,29111,H.p.-,54,M,upper abdominal pain,"gastritis, reflux, ösophagus varizen",not aplicable
6,P007-Z08,35447,H.p.-,50,M,upper abdominal pain,reflux,not aplicable
7,P001-Z13,36680,H.p.-,66,M,reflux,no finding,not aplicable
8,P004-Z17,39276,H.p.-,27,M,upper abdominal pain,no finding,not aplicable
9,P001-Z18,45063,H.p.-,50,M,unknown,reflux,not aplicable
10,P052-Z10,15743,H.p.+/CagA-,50,F,unknown,gastritis,3+
11,P107-Z15,16451,H.p.+/CagA-,51,M,reflux,"gastritis, reflux, hernia",2+
12,P033-Z12,26728,H.p.+/CagA-,66,F,unknown,"gastritis, reflux",1+
13,P008-Z17,26941,H.p.+/CagA-,34,F,upper abdominal pain,no finding,2+
14,P058-Z14,27627,H.p.+/CagA-,43,M,reflux,"gastritis, cardial insufficiency",3+
15,P080-Z15,44882,H.p.+/CagA-,76,F,upper abdominal pain,"gastritis, hernia",2+
16,P003-Z15,48255,H.p.+/CagA-,69,F,check-up,gastritis,2+
17,P022-Z12,48502,H.p.+/CagA-,75,F,unknown,"gastritis, hernia, duodenal inflammation",3+
18,P066-Z10,57636,H.p.+/CagA-,64,M,bleeding,"gastritis, hernia",2+
19,P022-Z13,188261,H.p.+/CagA-,71,F,check-up,gastritis,2+
20,P121-Z15,11223,H.p.+/CagA+,33,M,upper abdominal pain,gastritis,2+
21,P029-Z13,13309,H.p.+/CagA+,37,F,reflux,no finding,3+
22,P047-Z15,13310,H.p.+/CagA+,40,M,upper abdominal pain,"gastritis, ulcer duodenum",2+
23,P060-Z15,16297,H.p.+/CagA+,59,F,reflux,"gastritis, reflux",2+
24,P062-Z14,20451,H.p.+/CagA+,51,F,reflux,cardial insufficiency,3+
25,P021-Z12,27768,H.p.+/CagA+,21,F,irritable bowel syndrome,gastritis,3+
26,P008-Z08,33557,H.p.+/CagA+,32,M,upper abdominal pain,gastritis,3+
27,P022-Z17,59142,H.p.+/CagA+,50,M,anemia,no finding,2+
28,P061-Z10,73327,H.p.+/CagA+,32,F,irritable bowel syndrome,"gastritis, duodenal inflammation, lymphoedema",3+
29,P045-Z10-A,79271,H.p.+/CagA+,51,M,bleeding,gastritis,3+

In [ ]:
dft4['Taxon'][0]

'k__Bacteria;p__Proteobacteria;c__Betaproteobacteria;o__Burkholderiales;f__Oxalobacteraceae;g__'

In [ ]:
dfp.info()
dft1.info()
dft2.info()
dft3.info()
dft4.info()

<class 'pandas.core.frame.DataFrame'>
Index: 29 entries, 0 to 29
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Sample_ID       29 non-null     object
 1   Reads           29 non-null     int64
 2   Hp_CagA_Status  29 non-null     object
 3   Age             29 non-null     int64
 4   Sex             29 non-null     object
 5   Indication      29 non-null     object
 6   Diagnosis       29 non-null     object
 7   Score           29 non-null     object
dtypes: int64(2), object(6)
memory usage: 2.0+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 147 entries, 0 to 146
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   level       147 non-null    object
 1   taxon       147 non-null    object
 2   comparison  147 non-null    object
 3   mean1       147 non-null    object
 4   mean2       147 non-null    object
 5   pvalue      147 non-null    object
 6   adj.pvalue  147 non-null    object
 7   sig         84 non-null     object
dtypes: object(8)
memory usage: 9.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 314 entries, 0 to 313
Data columns (total 37 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   kingdom   314 non-null    object
 1   phylum    314 non-null    object
 2   class     314 non-null    object
 3   order     314 non-null    object
 4   family    314 non-null    object
 5   genus     314 non-null    object
 6   # OTUs    314 non-null    int64
 7   species   72 non-null     object
 8   P001Z12   314 non-null    float64
 9   P001Z13   314 non-null    float64
 10  P001Z14   314 non-null    float64
 11  P001Z18   314 non-null    float64
 12  P002Z18   314 non-null    float64
 13  P003Z10   314 non-null    float64
 14  P004Z17   314 non-null    float64
 15  P005Z08   314 non-null    float64
 16  P007Z08   314 non-null    float64
 17  P003Z15   314 non-null    float64
 18  P008Z17   314 non-null    float64
 19  P022Z12   314 non-null    float64
 20  P022Z13   314 non-null    float64
 21  P033Z12   314 non-null    float64
 22  P052Z10   314 non-null    float64
 23  P058Z14   314 non-null    float64
 24  P066Z10   314 non-null    float64
 25  P080Z15   314 non-null    float64
 26  P107Z15   314 non-null    float64
 27  P008Z08   314 non-null    float64
 28  P021Z12   314 non-null    float64
 29  P022Z17   314 non-null    float64
 30  P029Z13   314 non-null    float64
 31  P045Z10A  314 non-null    float64
 32  P047Z15   314 non-null    float64
 33  P060Z15   314 non-null    float64
 34  P061Z10   314 non-null    float64
 35  P062Z14   314 non-null    float64
 36  P121Z15   314 non-null    float64
dtypes: float64(29), int64(1), object(7)
memory usage: 90.9+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Type        9 non-null      object
 1   Comparison  9 non-null      object
 2   Effect      9 non-null      object
 3   SD          9 non-null      object
 4   N           9 non-null      object
dtypes: object(5)
memory usage: 492.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66 entries, 0 to 65
Data columns (total 32 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          65 non-null     float64
 1   Taxon       65 non-null     object
 2   P001Z12     66 non-null     float64
 3   P001Z13     66 non-null     float64
 4   P001Z14     66 non-null     float64
 5   P001Z18     66 non-null     float64
 6   P002Z18     66 non-null     float64
 7   P003Z10     66 non-null     float64
 8   P004Z17     66 non-null     float64
 9   P005Z08WH2  66 non-null     float64
 10  P007Z08     66 non-null     float64
 11  P003Z15     66 non-null     int64
 12  P008Z17     66 non-null     int64
 13  P022Z12     66 non-null     int64
 14  P022Z13     66 non-null     int64
 15  P033Z12     66 non-null     int64
 16  P052Z10     66 non-null     int64
 17  P058Z14     66 non-null     int64
 18  P066Z10     66 non-null     int64
 19  P080Z15     66 non-null     int64
 20  P107Z15     66 non-null     int64
 21  P008Z08     66 non-null     int64
 22  P021Z12     66 non-null     int64
 23  P022Z17     66 non-null     int64
 24  P029Z13     66 non-null     int64
 25  P045Z10A    66 non-null     int64
 26  P047Z15     66 non-null     int64
 27  P060Z15     66 non-null     int64
 28  P061Z10     66 non-null     int64
 29  P062Z14     66 non-null     int64
 30  P121Z15     66 non-null     int64
 31  Summe       65 non-null     float64
dtypes: float64(11), int64(20), object(1)
memory usage: 16.6+ KB

In [ ]:
dfp[["Reads", "Age", "Sex"]].groupby("Sex").mean().round(3)

         Reads     Age
Sex
F    39371.667  50.533
M    35531.786  47.643

In [ ]:
dfp[dfp["Sex"]=="M"]

,Sample_ID,Reads,Hp_CagA_Status,Age,Sex,Indication,Diagnosis,Score
2,P003-Z10,13651,H.p.-,56,M,upper abdominal pain,gastritis,not aplicable
5,P001-Z12,29111,H.p.-,54,M,upper abdominal pain,"gastritis, reflux, ösophagus varizen",not aplicable
6,P007-Z08,35447,H.p.-,50,M,upper abdominal pain,reflux,not aplicable
7,P001-Z13,36680,H.p.-,66,M,reflux,no finding,not aplicable
8,P004-Z17,39276,H.p.-,27,M,upper abdominal pain,no finding,not aplicable
9,P001-Z18,45063,H.p.-,50,M,unknown,reflux,not aplicable
11,P107-Z15,16451,H.p.+/CagA-,51,M,reflux,"gastritis, reflux, hernia",2+
14,P058-Z14,27627,H.p.+/CagA-,43,M,reflux,"gastritis, cardial insufficiency",3+
18,P066-Z10,57636,H.p.+/CagA-,64,M,bleeding,"gastritis, hernia",2+
20,P121-Z15,11223,H.p.+/CagA+,33,M,upper abdominal pain,gastritis,2+
22,P047-Z15,13310,H.p.+/CagA+,40,M,upper abdominal pain,"gastritis, ulcer duodenum",2+
26,P008-Z08,33557,H.p.+/CagA+,32,M,upper abdominal pain,gastritis,3+
27,P022-Z17,59142,H.p.+/CagA+,50,M,anemia,no finding,2+
29,P045-Z10-A,79271,H.p.+/CagA+,51,M,bleeding,gastritis,3+

In [ ]:
dfp[dfp["Sex"]=="F"]

,Sample_ID,Reads,Hp_CagA_Status,Age,Sex,Indication,Diagnosis,Score
0,P005-Z08,11346,H.p.-,23,F,celiac disease,no finding,not aplicable
1,P002-Z18,11460,H.p.-,38,F,reflux,"gastritis, reflux",not aplicable
3,P001-Z14,17305,H.p.-,56,F,upper abdominal pain,cardial insufficiency,not aplicable
10,P052-Z10,15743,H.p.+/CagA-,50,F,unknown,gastritis,3+
12,P033-Z12,26728,H.p.+/CagA-,66,F,unknown,"gastritis, reflux",1+
13,P008-Z17,26941,H.p.+/CagA-,34,F,upper abdominal pain,no finding,2+
15,P080-Z15,44882,H.p.+/CagA-,76,F,upper abdominal pain,"gastritis, hernia",2+
16,P003-Z15,48255,H.p.+/CagA-,69,F,check-up,gastritis,2+
17,P022-Z12,48502,H.p.+/CagA-,75,F,unknown,"gastritis, hernia, duodenal inflammation",3+
19,P022-Z13,188261,H.p.+/CagA-,71,F,check-up,gastritis,2+
21,P029-Z13,13309,H.p.+/CagA+,37,F,reflux,no finding,3+
23,P060-Z15,16297,H.p.+/CagA+,59,F,reflux,"gastritis, reflux",2+
24,P062-Z14,20451,H.p.+/CagA+,51,F,reflux,cardial insufficiency,3+
25,P021-Z12,27768,H.p.+/CagA+,21,F,irritable bowel syndrome,gastritis,3+
28,P061-Z10,73327,H.p.+/CagA+,32,F,irritable bowel syndrome,"gastritis, duodenal inflammation, lymphoedema",3+

In [ ]:
#Elimino helicobacter pylori porque puede sesgar el modelo al ser la especie más abundante.
#Sin embargo, en el paper de 2017 incluyen hp...
#If i keep this, i should always compare with bray curtis distances and clr transformations the full comunity, without hp not normalized and without hp renormalized.
dft2_nhp = dft2[dft2["genus"] != "g__Helicobacter"].copy()

In [ ]:
print(dfp[dfp['Hp_CagA_Status'] == 'H.p.-'].shape[0])
print(dfp[dfp['Hp_CagA_Status'] == 'H.p.+/CagA-'].shape[0])
print(dfp[dfp['Hp_CagA_Status'] == 'H.p.+/CagA+'].shape[0])

9
10
10

In [ ]:
display(dfp['Sample_ID'].head())

Voy a explorar la segunda tabla. Tenemos 313 taxa.

In [ ]:
print(f"Para un total de {dft2.shape[0]} taxones, excluyendo a H. pylori, se tienen:\n")

print(f"{dft2_nhp['phylum'].nunique()} phylum.")
print(f"{dft2_nhp['class'].nunique()} clases.")
print(f"{dft2_nhp['order'].nunique()} órdenes.")
print(f"{dft2_nhp['family'].nunique()} familias.")
print(f"{dft2_nhp['genus'].nunique()} géneros.")
print(f"{dft2_nhp['species'].nunique()} especies.")

Para un total de 314 taxones, excluyendo a H. pylori, se tienen:

19 phylum.
36 clases.
65 órdenes.
116 familias.
181 géneros.
66 especies.

In [ ]:
col_s_t2=dft2_nhp.columns[8:].tolist()
col_t_t2=dft2_nhp.columns[:8].tolist()
#Cálculo de riqueza observada, que realmente es
# número de taxa con abundancia mayor a cero.
(dft2_nhp[col_s_t2] > 0).sum().sort_values(ascending=False)
#De estos datos, P001Z14 tiene alta diversidad de taxa detectados, mientras
#P062Z14 tiene poca. A mayor número, mayor complejidad microbiana.

P001Z14     108
P001Z12      89
P001Z18      89
P007Z08      89
P066Z10      89
P001Z13      87
P004Z17      81
P107Z15      80
P008Z17      79
P008Z08      78
P003Z10      75
P058Z14      69
P121Z15      66
P005Z08      65
P080Z15      64
P003Z15      63
P060Z15      61
P002Z18      60
P045Z10A     60
P029Z13      59
P052Z10      58
P021Z12      58
P061Z10      56
P022Z17      53
P047Z15      42
P022Z13      40
P022Z12      40
P033Z12      40
P062Z14      36
dtype: int64

In [ ]:
#Im gonna melt dft2 sample columns to merge this df with dfp

dft2_nhp_n=pd.melt(dft2_nhp, id_vars=col_t_t2, value_vars=col_s_t2,var_name='Sample_ID', value_name='Abundances')
dfp_n=dfp.copy()
dfp_n["Sample_ID"] = dfp_n["Sample_ID"].str.replace('-', '', regex=False)
patients_status = dfp_n[['Sample_ID', 'Hp_CagA_Status', 'Score']]
dfp_m= pd.merge(dft2_nhp_n,patients_status,on="Sample_ID",how='left')
#The k__ etc is a taxonomy classidier for Greengenes/QIIME.
#Dont gonna use it here so imma remove it just to make life easier.
#Other is for unresolved taxonomy.
for col in col_t_t2[:-2]:
  #r'' standard for regex
  #^ start of the string, match only if appears at the begining
  #[a-z]__ any lower case letter followed by two underscores
  #regex=True regular expression
  dfp_m[col] = dfp_m[col].str.replace(r'^[a-z]__', '', regex=True)
display(dfp_m[['Sample_ID', 'Hp_CagA_Status', 'Score', 'kingdom', 'phylum', 'class', 'order', 'family', 'genus', 'species', '# OTUs', 'Abundances']])

,Sample_ID,Hp_CagA_Status,Score,kingdom,phylum,class,order,family,genus,species,# OTUs,Abundances
0,P001Z12,H.p.-,not aplicable,Bacteria,Firmicutes,Bacilli,Lactobacillales,Streptococcaceae,Streptococcus,s__alactolyticus;s__anginosus;s__infantis;s__s...,103,0.190581
1,P001Z12,H.p.-,not aplicable,Bacteria,Bacteroidetes,Bacteroidia,Bacteroidales,Prevotellaceae,Prevotella,s__copri;s__intermedia;s__melaninogenica;s__na...,86,0.139397
2,P001Z12,H.p.-,not aplicable,Bacteria,Actinobacteria,Actinobacteria,Actinomycetales,Actinomycetaceae,Actinomyces,NaN,50,0.048744
3,P001Z12,H.p.-,not aplicable,Bacteria,Firmicutes,Clostridia,Clostridiales,Lachnospiraceae,,NaN,33,0.002095
4,P001Z12,H.p.-,not aplicable,Bacteria,Firmicutes,Clostridia,Clostridiales,Veillonellaceae,Selenomonas,s__noxia,31,0.000172
...,...,...,...,...,...,...,...,...,...,...,...,...
9072,P121Z15,H.p.+/CagA+,2+,Bacteria,Synergistetes,Synergistia,Synergistales,Dethiosulfovibrionaceae,Pyramidobacter,s__piscolens,1,0.000000
9073,P121Z15,H.p.+/CagA+,2+,Bacteria,TM7,TM7-1,,,,NaN,1,0.000000
9074,P121Z15,H.p.+/CagA+,2+,Bacteria,TM7,TM7-3,Other,Other,Other,NaN,1,0.000000
9075,P121Z15,H.p.+/CagA+,2+,Bacteria,Tenericutes,Mollicutes,Acholeplasmatales,Acholeplasmataceae,,NaN,1,0.000000
9076,P121Z15,H.p.+/CagA+,2+,Bacteria,[Thermi],Deinococci,Deinococcales,Trueperaceae,Truepera,NaN,1,0.000000

In [ ]:
for col in col_t_t2[:-1]:
    print(col)
    print(dft2_nhp_n[col].value_counts().head())

kingdom
kingdom
k__Bacteria    9077
Name: count, dtype: int64
phylum
phylum
p__Proteobacteria    3509
p__Firmicutes        2320
p__Actinobacteria    1247
p__Bacteroidetes      928
p__TM7                174
Name: count, dtype: int64
class
class
c__Clostridia             1392
c__Alphaproteobacteria    1160
c__Gammaproteobacteria    1102
c__Actinobacteria         1102
c__Betaproteobacteria      928
Name: count, dtype: int64
order
order
o__Clostridiales      1392
o__Actinomycetales    1102
o__Rhizobiales         551
o__Burkholderiales     522
o__Lactobacillales     464
Name: count, dtype: int64
family
family
f__                   812
Other                 464
f__Lachnospiraceae    377
f__Veillonellaceae    261
f__Micrococcaceae     203
Name: count, dtype: int64
genus
genus
g__                 2668
Other               1218
g__Streptococcus      29
g__Actinomyces        29
g__Prevotella         29
Name: count, dtype: int64
# OTUs
# OTUs
1    4060
2    1624
3    1044
4     493
5     261
Name: count, dtype: int64

In [ ]:
# Fraction originally occupied by H. pylori
hp_fraction = 1 - dft2_nhp_n.groupby("Sample_ID")["Abundances"].sum()
hp_fraction.sort_values(ascending=False)

Sample_ID
P022Z12     9.930931e-01
P062Z14     9.847440e-01
P022Z13     9.814885e-01
P033Z12     9.789359e-01
P021Z12     9.774921e-01
P047Z15     9.685950e-01
P022Z17     9.642724e-01
P061Z10     9.517095e-01
P107Z15     9.412802e-01
P029Z13     9.124652e-01
P045Z10A    9.078099e-01
P052Z10     8.464079e-01
P008Z08     8.039157e-01
P058Z14     7.934629e-01
P060Z15     7.841320e-01
P121Z15     7.656598e-01
P008Z17     7.200178e-01
P066Z10     4.750850e-01
P080Z15     3.722428e-01
P003Z15     1.367112e-01
P003Z10     2.908212e-02
P002Z18     1.561955e-02
P007Z08     2.933958e-03
P001Z14     8.090147e-04
P001Z13     7.906216e-04
P004Z17     6.874427e-04
P001Z12     6.526742e-04
P001Z18     2.662939e-04
P005Z08    -2.109424e-14
Name: Abundances, dtype: float64

In [ ]:
f_wo_g = dft2[dft2['genus'] == 'g__']['family'].unique()
o_wo_f = dft2[dft2['family'] == 'f__']['order'].unique()
c_wo_o = dft2[dft2['order'] == 'o__']['class'].unique()
p_wo_c = dft2[dft2['class'] == 'c__']['phylum'].unique()

array(['p__SR1', 'p__Proteobacteria'], dtype=object)

In [ ]:
dfp_m.groupby("Sample_ID")["Abundances"].sum()

Sample_ID
P001Z12     0.999347
P001Z13     0.999209
P001Z14     0.999191
P001Z18     0.999734
P002Z18     0.984380
P003Z10     0.970918
P003Z15     0.863289
P004Z17     0.999313
P005Z08     1.000000
P007Z08     0.997066
P008Z08     0.196084
P008Z17     0.279982
P021Z12     0.022508
P022Z12     0.006907
P022Z13     0.018512
P022Z17     0.035728
P029Z13     0.087535
P033Z12     0.021064
P045Z10A    0.092190
P047Z15     0.031405
P052Z10     0.153592
P058Z14     0.206537
P060Z15     0.215868
P061Z10     0.048291
P062Z14     0.015256
P066Z10     0.524915
P080Z15     0.627757
P107Z15     0.058720
P121Z15     0.234340
Name: Abundances, dtype: float64

Estas abundancias deberían ser de ~100% por cada muestra, pero como eliminamos helicobacter pylori, esto es lo restante.

In [ ]:
dft2_nhp_n_rn=dft2_nhp_n.copy()
dft2_nhp_n_rn["Abundances"] = (
    dft2_nhp_n["Abundances"] /
    dft2_nhp_n.groupby("Sample_ID")["Abundances"].transform("sum")
)

In [ ]:
dfp_n_n=dfp.copy()
dfp_n_n["Sample_ID"] = dfp_n["Sample_ID"].str.replace('-', '', regex=False)
patients_status = dfp_n[['Sample_ID', 'Hp_CagA_Status', 'Score']]
dfp_m_n= pd.merge(dft2_nhp_n_rn,patients_status,on="Sample_ID",how='left')
#The k__ etc is a taxonomy classidier for Greengenes/QIIME.
#Dont gonna use it here so imma remove it just to make life easier.
#Other is for unresolved taxonomy.
for col in col_t_t2[:-2]:
  #r'' standard for regex
  #^ start of the string, match only if appears at the begining
  #[a-z]__ any lower case letter followed by two underscores
  #regex=True regular expression
  dfp_m_n[col] = dfp_m_n[col].str.replace(r'^[a-z]__', '', regex=True)
dfp_m_n.groupby("Sample_ID")["Abundances"].sum()

Sample_ID
P001Z12     1.0
P001Z13     1.0
P001Z14     1.0
P001Z18     1.0
P002Z18     1.0
P003Z10     1.0
P003Z15     1.0
P004Z17     1.0
P005Z08     1.0
P007Z08     1.0
P008Z08     1.0
P008Z17     1.0
P021Z12     1.0
P022Z12     1.0
P022Z13     1.0
P022Z17     1.0
P029Z13     1.0
P033Z12     1.0
P045Z10A    1.0
P047Z15     1.0
P052Z10     1.0
P058Z14     1.0
P060Z15     1.0
P061Z10     1.0
P062Z14     1.0
P066Z10     1.0
P080Z15     1.0
P107Z15     1.0
P121Z15     1.0
Name: Abundances, dtype: float64

In [ ]:
print(col_s_t2)
print(len(col_s_t2))
print(len(dft2.columns))

['P001Z12', 'P001Z13', 'P001Z14', 'P001Z18', 'P002Z18', 'P003Z10', 'P004Z17', 'P005Z08', 'P007Z08', 'P003Z15', 'P008Z17', 'P022Z12', 'P022Z13', 'P033Z12', 'P052Z10', 'P058Z14', 'P066Z10', 'P080Z15', 'P107Z15', 'P008Z08', 'P021Z12', 'P022Z17', 'P029Z13', 'P045Z10A', 'P047Z15', 'P060Z15', 'P061Z10', 'P062Z14', 'P121Z15']
29
37

In [ ]:
dft2[col_s_t2].sum()

P001Z12     0.999347
P001Z13     0.999209
P001Z14     0.999191
P001Z18     0.999734
P002Z18     0.984380
P003Z10     0.970918
P004Z17     0.999313
P005Z08     1.000000
P007Z08     0.997066
P003Z15     0.863289
P008Z17     0.279982
P022Z12     0.006907
P022Z13     0.018512
P033Z12     0.021064
P052Z10     0.153592
P058Z14     0.206537
P066Z10     0.524915
P080Z15     0.627757
P107Z15     0.058720
P008Z08     0.196084
P021Z12     0.022508
P022Z17     0.035728
P029Z13     0.087535
P045Z10A    0.092190
P047Z15     0.031405
P060Z15     0.215868
P061Z10     0.048291
P062Z14     0.015256
P121Z15     0.234340
dtype: float64

In [ ]:
dft2[col_s_t2].sum()

P001Z12     0.999382
P001Z13     0.999673
P001Z14     0.999827
P001Z18     0.999889
P002Z18     0.999127
P003Z10     1.000000
P004Z17     0.999313
P005Z08     1.000000
P007Z08     0.998561
P003Z15     0.999959
P008Z17     0.999926
P022Z12     0.999918
P022Z13     1.000000
P033Z12     1.000000
P052Z10     1.000000
P058Z14     1.000000
P066Z10     0.999098
P080Z15     0.999978
P107Z15     1.000000
P008Z08     0.999851
P021Z12     1.000000
P022Z17     1.000000
P029Z13     1.000000
P045Z10A    0.999962
P047Z15     1.000000
P060Z15     1.000000
P061Z10     1.000000
P062Z14     1.000000
P121Z15     1.000000
dtype: float64

Calcular:
- Alpha diversity (within-sample diversity - observed richness, shannon index, simpson index). <- Does hp reduce diversity?
- Beta diversity (microbial communities cluster by infection status? - bray-curtis distance, jaccard distance, permanova). <- Does hp shift global composition?
- Taxonomic composition differences (mean relative abundance by group, Wilcoxon test per taxon, FDR correction). <- which taxa drive differences?
- Compositional data analysis (CLR transformation, aitchison distance, pca on CLR).
- Relationships with the histological score (Spearman correlation between richness and score, kruskal-wallis test across score groups). <- does inflammation severity track microbiome change?

##Referencias.

Klymiuk, I., Bilgilier, C., Stadlmann, A., Thannesberger, J., Kastner, M., Högenauer, C., Püspök, A., Biowski-Frotz, S., Schrutka-Kölbl, C., Thallinger, G. G., & Steininger, C. (2017). The Human Gastric Microbiome Is Predicated upon Infection with Helicobacter pylori. Frontiers in Microbiology, 8, 2508. https://doi.org/10.3389/fmicb.2017.02508